ALTER TABLE TBL_LANE
 ADD (LANE_TYPE_ID  NUMBER(1) DEFAULT 1);

 ALTER TABLE TBL_TRANSACTION
 ADD (IS_REGISTERED  NUMBER(1) DEFAULT 0);
 
  ALTER TABLE TBL_TRANSACTION
 ADD (VEHICLESPEED  DECIMAL(5,2) DEFAULT 0);

ALTER TABLE TBL_NODEFLUX_PACKET ADD  PROVIDER NUMBER(1);

