/* Formatted on 05/02/2019 17:37:58 (QP5 v5.215.12089.38647) */
DROP VIEW TRANS_UNREVIEWED;

CREATE VIEW TRANS_UNREVIEWED
AS
     SELECT T.TMS_ID,
            T.PLAZA_ID,
            P.PLAZA_NAME,
            T.LANE_ID,
            L.LANE_NAME,
            T.TRANSACTION_ID,
            T.TRANSACTION_DATETIME,
            TO_CHAR (T.TRANSACTION_DATETIME, 'DD-Mon-YYYY HH:MI:SS AM')
               F_TRANSACTION_DATETIME,
            (CASE NVL (T.CT_ENTRY_ID, 0)
                WHEN 0 THEN T.CT_ENTRY_ID_REAR
                ELSE T.CT_ENTRY_ID
             END)
               CT_ENTRY_ID,
            T.NF_ENTRY_ID_FRONT,
            T.NF_ENTRY_ID_REAR,
            T.IS_BALANCE_UPDATED,
            T.IS_TRANSFERED,
            T.IS_VIOLATION,
            T.IS_REGISTERED,
            T.AUDIT_STATUS,
            T.AUDITOR_ID,
            T.AUDIT_DATE,
            T.AUDITED_VEHICLE_CLASS_ID,
            T.AUDITED_VRN,
            T.VEHICLESPEED,
            T.MEARGED_TRAN_ID
       FROM TBL_TRANSACTION T
            LEFT OUTER JOIN TBL_PLAZA P
               ON T.PLAZA_ID = P.PLAZA_ID
            LEFT OUTER JOIN TBL_LANE L
               ON T.LANE_ID = L.LANE_ID
      WHERE NVL (T.IS_BALANCE_UPDATED, 2) <> 1 AND NVL (T.AUDIT_STATUS, 2) <> 1
   ORDER BY T.TRANSACTION_ID DESC;



DROP VIEW TRANS_REVIEWED;

CREATE VIEW TRANS_REVIEWED
AS
     SELECT T.TMS_ID,
            T.PLAZA_ID,
            P.PLAZA_NAME,
            T.LANE_ID,
            L.LANE_NAME,
            T.TRANSACTION_ID,
            T.TRANSACTION_DATETIME,
            TO_CHAR (T.TRANSACTION_DATETIME, 'DD-Mon-YYYY HH:MI:SS AM')
               F_TRANSACTION_DATETIME,
            (CASE NVL (T.CT_ENTRY_ID, 0)
                WHEN 0 THEN T.CT_ENTRY_ID_REAR
                ELSE T.CT_ENTRY_ID
             END)
               CT_ENTRY_ID,
            T.NF_ENTRY_ID_FRONT,
            T.NF_ENTRY_ID_REAR,
            T.IS_REGISTERED,
            T.VEHICLESPEED,
            T.AUDITOR_ID,
            T.AUDIT_DATE,
            T.AUDITED_VEHICLE_CLASS_ID,
            T.AUDITED_VRN,
            T.MEARGED_TRAN_ID,
            T.TRANS_STATUS,
            (CASE TRANS_STATUS
                WHEN 1 THEN 'Charged'
                WHEN 2 THEN 'Merged'
                WHEN 3 THEN 'Violation'
                WHEN 4 THEN 'Unidentified'
                ELSE 'Unknown'
             END)
               TRANS_STATUS_NAME
       FROM TBL_TRANSACTION T
            LEFT OUTER JOIN TBL_PLAZA P
               ON T.PLAZA_ID = P.PLAZA_ID
            LEFT OUTER JOIN TBL_LANE L
               ON T.LANE_ID = L.LANE_ID
      WHERE NVL (T.AUDIT_STATUS, 2) = 1
   ORDER BY T.AUDIT_DATE DESC;

  DROP VIEW TRANS_CHARGED;

CREATE VIEW TRANS_CHARGED
AS
     SELECT T.TMS_ID,
            T.PLAZA_ID,
            P.PLAZA_NAME,
            T.LANE_ID,
            L.LANE_NAME,
            T.TRANSACTION_ID,
            T.TRANSACTION_DATETIME,
            TO_CHAR (T.TRANSACTION_DATETIME, 'DD-Mon-YYYY HH:MI:SS AM')
               F_TRANSACTION_DATETIME,
            (CASE NVL (T.CT_ENTRY_ID, 0)
                WHEN 0 THEN T.CT_ENTRY_ID_REAR
                ELSE T.CT_ENTRY_ID
             END)
               CT_ENTRY_ID,
            T.NF_ENTRY_ID_FRONT,
            T.NF_ENTRY_ID_REAR,
            T.IS_BALANCE_UPDATED,
            T.IS_TRANSFERED,
            T.IS_VIOLATION,
            T.IS_REGISTERED,
            T.AUDIT_STATUS,
            T.AUDITOR_ID,
            T.AUDIT_DATE,
            T.AUDITED_VEHICLE_CLASS_ID,
            T.AUDITED_VRN,
            T.VEHICLESPEED,
            T.MEARGED_TRAN_ID,
            (CASE NVL (T.AUDIT_STATUS, 0) WHEN 0 THEN 'Auto' ELSE 'Manual' END)
               TSOURCE,
            NVL (SH.GATEWAY_RESPONSE_CODE, 0) GATEWAY_RESPONSE_CODE,
            NVL (SH.OPERATOR_RESPONSE_CODE, 0) OPERATOR_RESPONSE_CODE,
            (CASE NVL (SH.OPERATOR_RESPONSE_CODE, 0)
                WHEN 0 THEN 'blank'
                WHEN 1 THEN 'Pending'
                WHEN 2 THEN 'Delivered'
                WHEN 3 THEN 'Read'
                WHEN 4 THEN 'Rejected'
                WHEN 5 THEN 'Failed'
             END)
               OPERATOR_RESPONSE_TEXT
       FROM TBL_TRANSACTION T
            LEFT OUTER JOIN TBL_PLAZA P
               ON T.PLAZA_ID = P.PLAZA_ID
            LEFT OUTER JOIN TBL_LANE L
               ON T.LANE_ID = L.LANE_ID
            LEFT OUTER JOIN TBL_ACCOUNT_HISTORY AH
               ON T.TRANSACTION_ID = AH.TRANSACTION_ID
            LEFT OUTER JOIN TBL_SMS_COMM_HISTORY SH
               ON AH.ENTRY_ID = SH.ACCOUNT_HISTORY_ID
      WHERE NVL (T.IS_BALANCE_UPDATED, 0) = 1
   ORDER BY T.TRANSACTION_DATETIME DESC;

  DROP VIEW TRANS_VIOLATION;

CREATE VIEW TRANS_VIOLATION
AS
     SELECT T.TMS_ID,
            T.PLAZA_ID,
            P.PLAZA_NAME,
            T.LANE_ID,
            L.LANE_NAME,
            T.TRANSACTION_ID,
            T.TRANSACTION_DATETIME,
            TO_CHAR (T.TRANSACTION_DATETIME, 'DD-Mon-YYYY HH:MI:SS AM')
               F_TRANSACTION_DATETIME,
            T.CT_ENTRY_ID,
            T.NF_ENTRY_ID_FRONT,
            T.NF_ENTRY_ID_REAR,
            T.IS_BALANCE_UPDATED,
            T.IS_TRANSFERED,
            T.IS_VIOLATION,
            T.IS_REGISTERED,
            T.AUDIT_STATUS,
            T.AUDITOR_ID,
            T.AUDIT_DATE,
            T.AUDITED_VEHICLE_CLASS_ID,
            T.AUDITED_VRN,
            T.VEHICLESPEED,
            T.MEARGED_TRAN_ID
       FROM TBL_TRANSACTION T
            LEFT OUTER JOIN TBL_PLAZA P
               ON T.PLAZA_ID = P.PLAZA_ID
            LEFT OUTER JOIN TBL_LANE L
               ON T.LANE_ID = L.LANE_ID
      WHERE NVL (T.AUDIT_STATUS, 2) = 1 AND NVL (T.IS_VIOLATION, 0) = 1
   ORDER BY T.AUDIT_DATE DESC;

DROP VIEW TRANS_UNIDENTIFIED;

CREATE VIEW TRANS_UNIDENTIFIED
AS
     SELECT T.TMS_ID,
            T.PLAZA_ID,
            P.PLAZA_NAME,
            T.LANE_ID,
            L.LANE_NAME,
            T.TRANSACTION_ID,
            T.TRANSACTION_DATETIME,
            TO_CHAR (T.TRANSACTION_DATETIME, 'DD-Mon-YYYY HH:MI:SS AM')
               F_TRANSACTION_DATETIME,
            T.CT_ENTRY_ID,
            T.NF_ENTRY_ID_FRONT,
            T.NF_ENTRY_ID_REAR,
            T.IS_BALANCE_UPDATED,
            T.IS_TRANSFERED,
            T.IS_VIOLATION,
            T.IS_REGISTERED,
            T.AUDIT_STATUS,
            T.AUDITOR_ID,
            T.AUDIT_DATE,
            T.AUDITED_VEHICLE_CLASS_ID,
            T.AUDITED_VRN,
            T.VEHICLESPEED,
            T.MEARGED_TRAN_ID
       FROM TBL_TRANSACTION T
            LEFT OUTER JOIN TBL_PLAZA P
               ON T.PLAZA_ID = P.PLAZA_ID
            LEFT OUTER JOIN TBL_LANE L
               ON T.LANE_ID = L.LANE_ID
      WHERE     NVL (T.AUDIT_STATUS, 2) = 1
            AND NVL (T.AUDITED_VEHICLE_CLASS_ID, 0) = 0
   ORDER BY T.AUDIT_DATE DESC;


DROP VIEW TRANS_TOPUP;

CREATE VIEW TRANS_TOPUP
AS
   SELECT ENTRY_ID,
          ACCOUNT_ID,
          CUSTOMER_VEHICLE_ENTRY_ID,
          AMOUNT,
          CREATION_DATE,
          TO_CHAR (CREATION_DATE, 'DD-Mon-YYYY HH:MI:SS AM') F_CREATION_DATE
     FROM TBL_ACCOUNT_HISTORY
    WHERE TRANSACTION_TYPE = 2 AND NVL (CUSTOMER_VEHICLE_ENTRY_ID, 0) <> 0;

DROP VIEW SMS_SEND_GATWAY;

CREATE VIEW SMS_SEND_GATWAY
AS
   SELECT SC.ENTRY_ID,
          SC.TMS_ID,
          SC.CUSTOMER_ACCOUNT_ID,
          SC.CUSTOMER_NAME,
          SC.MOBILE_NUMBER,
          SC.MESSAGE_DIRECTION,
          SC.MESSAGE_BODY,
          SC.SENT_STATUS,
          SC.RECEIVED_PROCESS_STATUS,
          SC.MESSAGE_SEND_TIME,
          SC.MESSAGE_RECEIVE_TIME,
          SC.MESSAGE_DELIVERY_STATUS,
          SC.ATTEMPT_COUNT,
          SC.CREATION_DATE,
          SC.MODIFICATION_DATE,
          SC.MODIFIED_BY,
          SC.GATEWAY_RESPONSE_CODE,
          SC.OPERATOR_RESPONSE_CODE,
          AH.TRANSACTION_TYPE,
          (CASE AH.TRANSACTION_TYPE
              WHEN 1 THEN 'Sale'
              WHEN 2 THEN 'Top-Up'
              WHEN 3 THEN 'Refund'
              WHEN 4 THEN 'Charge'
           END)
             TRANSACTION_SUBJECT,
          EMAIL_ID,
          SC.TRANSACTION_ID,
          '' VEHICLE_RC_NO
     FROM TBL_SMS_COMM_HISTORY SC
          LEFT OUTER JOIN TBL_ACCOUNT_HISTORY AH
             ON SC.ACCOUNT_HISTORY_ID = AH.ENTRY_ID
          LEFT OUTER JOIN TBL_CUSTOMER_ACCOUNT CA
             ON SC.CUSTOMER_ACCOUNT_ID = CA.ACCOUNT_ID
    WHERE     SC.SENT_STATUS = 1
          AND SC.MESSAGE_DIRECTION = 2
          AND NVL (GATEWAY_RESPONSE_CODE, 0) = 0;



DROP VIEW SMS_PENDING_GATWAY_STATUS;

CREATE VIEW SMS_PENDING_GATWAY_STATUS
AS
   SELECT SC.ENTRY_ID,
          SC.TMS_ID,
          SC.CUSTOMER_ACCOUNT_ID,
          SC.CUSTOMER_NAME,
          SC.MOBILE_NUMBER,
          SC.MESSAGE_DIRECTION,
          SC.MESSAGE_BODY,
          SC.SENT_STATUS,
          SC.RECEIVED_PROCESS_STATUS,
          SC.MESSAGE_SEND_TIME,
          SC.MESSAGE_RECEIVE_TIME,
          SC.MESSAGE_DELIVERY_STATUS,
          SC.ATTEMPT_COUNT,
          SC.CREATION_DATE,
          SC.MODIFICATION_DATE,
          SC.MODIFIED_BY,
          SC.GATEWAY_RESPONSE_CODE,
          SC.OPERATOR_RESPONSE_CODE,
          AH.TRANSACTION_TYPE,
          (CASE AH.TRANSACTION_TYPE
              WHEN 1 THEN 'Sale'
              WHEN 2 THEN 'Top-Up'
              WHEN 3 THEN 'Refund'
              WHEN 4 THEN 'Charge'
           END)
             TRANSACTION_SUBJECT,
          EMAIL_ID,
          SC.TRANSACTION_ID,
          '' VEHICLE_RC_NO
     FROM TBL_SMS_COMM_HISTORY SC
          LEFT OUTER JOIN TBL_ACCOUNT_HISTORY AH
             ON SC.ACCOUNT_HISTORY_ID = AH.ENTRY_ID
          LEFT OUTER JOIN TBL_CUSTOMER_ACCOUNT CA
             ON SC.CUSTOMER_ACCOUNT_ID = CA.ACCOUNT_ID
    WHERE     SC.SENT_STATUS = 2
          AND SC.MESSAGE_DIRECTION = 2
          AND NVL (OPERATOR_RESPONSE_CODE, 0) IN (0, 1, 5)
          AND NVL (GATEWAY_RESPONSE_CODE, 0) = 1701;

DROP VIEW MOBILE_PENDING_NOTIFICATION;

CREATE VIEW MOBILE_PENDING_NOTIFICATION
AS
   SELECT SC.ENTRY_ID,
          SC.TMS_ID,
          SC.CUSTOMER_ACCOUNT_ID,
          SC.CUSTOMER_NAME,
          SC.MOBILE_NUMBER,
          SC.MESSAGE_DIRECTION,
          SC.MESSAGE_BODY,
          SC.SENT_STATUS,
          SC.RECEIVED_PROCESS_STATUS,
          SC.MESSAGE_SEND_TIME,
          SC.MESSAGE_RECEIVE_TIME,
          SC.MESSAGE_DELIVERY_STATUS,
          SC.ATTEMPT_COUNT,
          SC.CREATION_DATE,
          SC.MODIFICATION_DATE,
          SC.MODIFIED_BY,
          SC.GATEWAY_RESPONSE_CODE,
          SC.OPERATOR_RESPONSE_CODE,
          AH.TRANSACTION_TYPE,
          (CASE AH.TRANSACTION_TYPE
              WHEN 1 THEN 'Sale'
              WHEN 2 THEN 'Top-Up'
              WHEN 3 THEN 'Refund'
              WHEN 4 THEN 'Charge'
           END)
             TRANSACTION_SUBJECT,
          EMAIL_ID,
          SC.TRANSACTION_ID,
          CV.VEHICLE_RC_NO,
          CA.RESIDENT_ID,
          CV.ENTRY_ID AS VEHICLEID
     FROM TBL_SMS_COMM_HISTORY SC
          LEFT OUTER JOIN TBL_ACCOUNT_HISTORY AH
             ON SC.ACCOUNT_HISTORY_ID = AH.ENTRY_ID
          LEFT OUTER JOIN TBL_CUSTOMER_ACCOUNT CA
             ON SC.CUSTOMER_ACCOUNT_ID = CA.ACCOUNT_ID
          LEFT OUTER JOIN TBL_CUSTOMER_VEHICLE CV
             ON AH.CUSTOMER_VEHICLE_ENTRY_ID = CV.ENTRY_ID
    WHERE     SC.MESSAGE_DIRECTION = 2
          AND NVL (SC.MOBILE_SEND_STATUS, 1) = 1
          AND NVL (CV.VEHICLE_RC_NO, '') <> '';

DROP VIEW TRANS_DEATILS;

CREATE VIEW TRANS_DEATILS
AS
   SELECT T.TMS_ID,
          T.PLAZA_ID,
          T.LANE_ID,
          T.TRANSACTION_ID,
          T.TRANSACTION_DATETIME,
          T.CREATION_DATE,
          T.VEHICLESPEED,
          T.CT_ENTRY_ID AS RFID_FRONT_ID,
          CTP.TIME_STAMP AS RFID_FRONT_TIMESTAMP,
          CTP.OBJECT_ID AS RFID_FRONT_TAG_ID,
          CTP.CTP.VEHICLE_CLASS_ID AS RFID_FRONT_CLASS_ID,
          CTP.PLATE_NUMBER AS RFID_FRONT_VRN,
          T.CT_ENTRY_ID_REAR AS RFID_REAR_ID,
          CTPR.TIME_STAMP AS RFID_REAR_TIMESTAMP,
          CTPR.OBJECT_ID AS RFID_REAR_TAG_ID,
          CTPR.VEHICLE_CLASS_ID AS RFID_REAR_CLASS_ID,
          CTPR.PLATE_NUMBER AS RFID_REAR_VRN,
          T.NF_ENTRY_ID_FRONT AS ANPR_FRONT_ID,
          NFPF.PLATE_NUMBER AS ANPR_FRONT_VRN,
          NFPF.VEHICLE_CLASS_ID AS ANPR_FRONT_CLASS_ID,
          NFPF.PLATE_THUMBNAIL AS ANPR_FRONT_IMAGE,
          NFPF.VIDEO_URL AS ANPR_FRONT_VIDEO_URL,
          NFPF.VEHICLE_SPEED AS ANPR_FRONT_SPEED,
          T.NF_ENTRY_ID_REAR AS ANPR_REAR_ID,
          NFPR.PLATE_NUMBER AS ANPR_REAR_VRN,
          NFPR.VEHICLE_CLASS_ID AS ANPR_REAR_CLASS_ID,
          NFPR.PLATE_THUMBNAIL AS ANPR_REAR_IMAGE,
          NFPR.VIDEO_URL AS ANPR_REAR_VIDEO_URL,
          NFPR.VEHICLE_SPEED AS ANPR_REAR_SPEED,
          T.IS_BALANCE_UPDATED,
          T.IS_VIOLATION,
          T.IS_REGISTERED,
          T.AUDIT_STATUS,
          T.AUDITOR_ID,
          T.AUDIT_DATE,
          T.AUDITED_VEHICLE_CLASS_ID,
          T.AUDITED_VRN,
          AH.AMOUNT,
          AH.CLOSING_BALANCE,
          T.MEARGED_TRAN_ID AS ParentId,
          T.TRANS_STATUS,
          NVL (SH.GATEWAY_RESPONSE_CODE, 0) GATEWAY_RESPONSE_CODE,
          NVL (SH.OPERATOR_RESPONSE_CODE, 0) OPERATOR_RESPONSE_CODE
     FROM TBL_TRANSACTION T
          LEFT OUTER JOIN TBL_PLAZA P
             ON T.PLAZA_ID = P.PLAZA_ID
          LEFT OUTER JOIN TBL_LANE L
             ON T.LANE_ID = L.LANE_ID
          LEFT OUTER JOIN TBL_CROSSTALK_PACKET CTP
             ON T.CT_ENTRY_ID = CTP.ENTRY_ID
          LEFT OUTER JOIN TBL_VEHICLE_CLASS VC_CTP
             ON VC_CTP.VEHICLE_CLASS_ID = CTP.VEHICLE_CLASS_ID
          LEFT OUTER JOIN TBL_CROSSTALK_PACKET CTPR
             ON T.CT_ENTRY_ID_REAR = CTPR.ENTRY_ID
          LEFT OUTER JOIN TBL_VEHICLE_CLASS VC_CTPR
             ON VC_CTPR.VEHICLE_CLASS_ID = CTPR.VEHICLE_CLASS_ID
          LEFT OUTER JOIN TBL_NODEFLUX_PACKET NFPF
             ON T.NF_ENTRY_ID_FRONT = NFPF.ENTRY_ID
          LEFT OUTER JOIN TBL_CUSTOMER_VEHICLE CV_NFPF
             ON CV_NFPF.VEH_REG_NO = NFPF.PLATE_NUMBER
          LEFT OUTER JOIN TBL_VEHICLE_CLASS VC_NFPF
             ON NFPF.VEHICLE_CLASS_ID = VC_NFPF.VEHICLE_CLASS_ID
          LEFT OUTER JOIN TBL_NODEFLUX_PACKET NFPR
             ON T.NF_ENTRY_ID_REAR = NFPR.ENTRY_ID
          LEFT OUTER JOIN TBL_CUSTOMER_VEHICLE CV_NFPR
             ON CV_NFPR.VEH_REG_NO = NFPR.PLATE_NUMBER
          LEFT OUTER JOIN TBL_VEHICLE_CLASS VC_NFPR
             ON NFPR.VEHICLE_CLASS_ID = VC_NFPR.VEHICLE_CLASS_ID
          LEFT OUTER JOIN TBL_ACCOUNT_HISTORY AH
             ON T.TRANSACTION_ID = AH.TRANSACTION_ID
          LEFT OUTER JOIN TBL_SMS_COMM_HISTORY SH
             ON AH.ENTRY_ID = SH.ACCOUNT_HISTORY_ID;