TRUNCATE TABLE TBL_CROSSTALK_PACKET;

DROP SEQUENCE CROSSTALK_PACKET_SEQ;
 
CREATE SEQUENCE CROSSTALK_PACKET_SEQ
   START WITH 1
   MAXVALUE 9999999999
   MINVALUE 1
   NOCYCLE
   NOCACHE
   NOORDER;

TRUNCATE TABLE  TBL_NODEFLUX_PACKET  ;

DROP SEQUENCE NODEFLUX_PACKET_SEQ;
	
CREATE SEQUENCE NODEFLUX_PACKET_SEQ
   START WITH 1
   MAXVALUE 9999999999
   MINVALUE 1
   NOCYCLE
   NOCACHE
   NOORDER;

  TRUNCATE TABLE  TBL_SMS_COMM_HISTORY; 
   
 DROP SEQUENCE SMS_COMM_HISTORY_SEQ;
   
CREATE SEQUENCE SMS_COMM_HISTORY_SEQ
   START WITH 1
   MAXVALUE 9999999999
   MINVALUE 1
   NOCYCLE
   NOCACHE
   NOORDER;

TRUNCATE TABLE  TBL_CUSTOMER_ACCOUNT;

 DROP SEQUENCE CUSTOMER_ACCOUNT_SEQ;
	
CREATE SEQUENCE CUSTOMER_ACCOUNT_SEQ
   START WITH 1
   MAXVALUE 9999999999
   MINVALUE 1
   NOCYCLE
   NOCACHE
   NOORDER;

TRUNCATE TABLE  TBL_TRANSACTION;   
   
DROP SEQUENCE TRANSACTION_SEQ;

CREATE SEQUENCE TRANSACTION_SEQ
   START WITH 1
   MAXVALUE 9999999999
   MINVALUE 1
   NOCYCLE
   NOCACHE
   NOORDER;

TRUNCATE TABLE  TBL_ACCOUNT_HISTORY  ;
   
DROP SEQUENCE ACCOUNT_HISTORY_SEQ;

CREATE SEQUENCE ACCOUNT_HISTORY_SEQ
   START WITH 1
   MAXVALUE 9999999999
   MINVALUE 1
   NOCYCLE
   NOCACHE
   NOORDER;

   


