DROP SEQUENCE CROSSTALK_PACKET_SEQ;
 
CREATE SEQUENCE CROSSTALK_PACKET_SEQ
   START WITH 1
   MAXVALUE 9999999999
   MINVALUE 1
   NOCYCLE
   NOCACHE
   NOORDER;

DROP SEQUENCE NODEFLUX_PACKET_SEQ;
	
CREATE SEQUENCE NODEFLUX_PACKET_SEQ
   START WITH 1
   MAXVALUE 9999999999
   MINVALUE 1
   NOCYCLE
   NOCACHE
   NOORDER;

 DROP SEQUENCE SMS_COMM_HISTORY_SEQ;
   
CREATE SEQUENCE SMS_COMM_HISTORY_SEQ
   START WITH 1
   MAXVALUE 9999999999
   MINVALUE 1
   NOCYCLE
   NOCACHE
   NOORDER;


 DROP SEQUENCE CUSTOMER_ACCOUNT_SEQ;
	
CREATE SEQUENCE CUSTOMER_ACCOUNT_SEQ
   START WITH 1
   MAXVALUE 9999999999
   MINVALUE 1
   NOCYCLE
   NOCACHE
   NOORDER;

DROP SEQUENCE TRANSACTION_SEQ;

CREATE SEQUENCE TRANSACTION_SEQ
   START WITH 1
   MAXVALUE 9999999999
   MINVALUE 1
   NOCYCLE
   NOCACHE
   NOORDER;

DROP SEQUENCE ACCOUNT_HISTORY_SEQ;

CREATE SEQUENCE ACCOUNT_HISTORY_SEQ
   START WITH 1
   MAXVALUE 9999999999
   MINVALUE 1
   NOCYCLE
   NOCACHE
   NOORDER;

   


DROP SEQUENCE ACCOUNT_HISTORY_SEQ;

 CREATE SEQUENCE ACCOUNT_HISTORY_SEQ
   START WITH 1
   MAXVALUE 9999999999
   MINVALUE 1
   NOCYCLE
   NOCACHE
   NOORDER;